### ISSUE TITLE
authenticate using x509 Membership Authentication

### ISSUE THREAD

**Issue by fischerscode** [ansible-collections/community.mongodb#177]
##### SUMMARY
For setting up a mongodb, being able to authenticate using the [x509 Membership Authentication](https://docs.mongodb.com/manual/tutorial/configure-x509-member-authentication/) would be quite useful, as it would allow secure authentication before any user is configured.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mongodb_common

##### ADDITIONAL INFORMATION
This feature could be used to configure a cluster from the first second with little preparation, in addition to that, the cluster could be set up without restarting any node, as authentication could be enabled at the first boot.

When implemented, the plugins could be used for doing something like this:
```yaml
- name: create admin user
  command: |
    /usr/bin/mongo mongodb-host.test \
          --tls \
          --tlsCAFile /tmp/ca.crt \
          --tlsCertificateKeyFile=/tmp/tls.key \
          --authenticationMechanism MONGODB-X509 \
          --authenticationDatabase '$external' \
          --eval \
          '{{ lookup('template', 'templates/create-admin-user.js') }}'
  register: mongoout
  changed_when: "'{ \0ok\0 : 1 }' in mongoout.stdout"
```

[Mongopy](https://api.mongodb.com/python/current/examples/authentication.html#mongodb-x509) seems to support this.
The [mongodb doc](https://docs.mongodb.com/manual/tutorial/configure-x509-member-authentication/) for x509 membership authentication.

**Comment by rhysmeister** [comment]
All modules support the following ssl options...

```
ssl (False, bool, False)
Whether to use an SSL connection when connecting to the database.
ssl_cert_reqs (False, str, CERT_REQUIRED)
Specifies whether a certificate is required from the other side of the connection, and whether it will be validated if provided.
ssl_ca_certs (False, str, None)
The ssl_ca_certs option takes a path to a CA file.
ssl_crlfile (False, str, None)
The ssl_crlfile option takes a path to a CRL file.
ssl_certfile (False, str, None)
Present a client certificate using the ssl_certfile option.
ssl_keyfile (False, str, None)
Private key for the client certificate.
ssl_pem_passphrase (False, str, None)
Passphrase to decrypt encrypted private keys.
```

The documentation states these provide the same functionality as the tls options...

`Starting in version 4.2, MongoDB provides net.tls settings (and corresponding command-line options) that corresponds to the net.ssl settings (and their corresponding command-line options). The net.tls settings provide identical functionality as the net.ssl options since MongoDB has always supported TLS 1.0 and later.`

https://docs.mongodb.com/manual/tutorial/configure-ssl/#procedures-using-net-ssl-settings

Is there anything missing meaning your above approach won't  work?

**Comment by fischerscode** [comment]
As far as I know, there is a difference between [Membership Authentication](https://docs.mongodb.com/manual/tutorial/configure-x509-member-authentication/) and [Client Authentication](https://docs.mongodb.com/manual/tutorial/configure-x509-client-authentication/).
I think, the provided ssl options only work for client authentication.

I am able to create a a user using this task through x509 Membership Authentication.
```yaml
- name: create admin user
  command: |
    /usr/bin/mongo mongodb-host.test \
          --tls \
          --tlsCAFile /tmp/ca.crt \
          --tlsCertificateKeyFile=/tmp/tls.key \
          --authenticationMechanism MONGODB-X509 \
          --authenticationDatabase '$external' \
          --eval \
          '{{ lookup('template', 'templates/create-admin-user.js') }}'
  register: mongoout
  changed_when: "'{ \0ok\0 : 1 }' in mongoout.stdout"
```
and this fails for me with: `fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to add or update user: 'ServerSelectionTimeoutError' object has no attribute 'code'"}`
```yaml
- name: create admin user
  community.mongodb.mongodb_user:
    login_host: "mongodb-host.test"
    login_port: 27001
    login_database: "$external"
    database: "admin"
    name: "admin"
    password: "{{admin_password}}"
    roles:
      - dbAdminAnyDatabase
    ssl: true
    ssl_ca_certs: "/tmp/ca.crt"
    ssl_certfile: "/tmp/tls.key"
    state: present
```
But maybe I am just missing something.

**Comment by rhysmeister** [comment]
Well... you've found a bug here I need to fix.

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to add or update user: 'ServerSelectionTimeoutError' object has no attribute 'code'"}
```

ssl/tls are definitely the same thing as far as I can see in the documentation. We don't specify authenticationMechanism anywhere in the mongodb module so your example would be attempting with the default (SCRAM). It should be fairly simple to add this to the modules as follows...

```
- name: create admin user
  community.mongodb.mongodb_user:
    login_host: "mongodb-host.test"
    login_port: 27001
    login_database: "$external"
    database: "admin"
    name: "admin"
    password: "{{admin_password}}"
    roles:
      - dbAdminAnyDatabase
    ssl: true
    ssl_ca_certs: "/tmp/ca.crt"
    ssl_certfile: "/tmp/tls.key"
    auth_mechanism: "MONGODB-X509"
    state: present
```
I probably need to add the mechanisms from here...

https://api.mongodb.com/python/current/examples/authentication.html

and probably remove the auth database from the arguments when x.509 is used. Should be able to get this done in the next day or two.

Cheers,

Rhys

**Comment by fischerscode** [comment]
Nice, thank you! 👍

**Comment by rhysmeister** [comment]
I've added the auth_mechanism feature in the following pr...

https://github.com/ansible-collections/community.mongodb/pull/179

Assuming I'm correct in my assumptions this should work. I don't currently have the ability to easily test this. If you are able to do so that would be helpful.

**Comment by fischerscode** [comment]
Thank you 👍 
I'll be happy to test it.

**Comment by fischerscode** [comment]
Unfortunately I have not been able to make it work.
I have tried different combinations like this:
```
     community.mongodb.mongodb_user:
       login_host: "mongodb-host.test"
       login_port: 27001
       login_database: "$external"
       database: "admin"
       name: "admin"
       password: "test"
       roles:
        - dbAdminAnyDatabase
       ssl: true
       ssl_ca_certs: "/tmp/ca.crt"
       ssl_certfile: "/tmp/tls.key" #cert and key in one file
       state: present
       auth_mechanism: "MONGODB-X509"
```
I am still getting this this error:
`fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "msg": "Unable to add or update user: 'ServerSelectionTimeoutError' object has no attribute 'code'"}`
