### ISSUE TITLE
Build and Publish Collection seems to be failing without error

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.mongodb#202]
##### SUMMARY
https://github.com/ansible-collections/community.mongodb/releases/tag/latest - "Latest" release is 19 days ago although the workflow runs without error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
publish_collection.yml

##### STEPS TO REPRODUCE
Merge a pull request to master
##### EXPECTED RESULTS
Workflow should build and publish result to a release called "latest".

##### ACTUAL RESULTS
Workflow run without error but "latest" release is not updated...

https://github.com/ansible-collections/community.mongodb/runs/1191933856?check_suite_focus=true

I would guess there's something wrong with the "Upload files to release" step.

**Comment by cognifloyd** [comment]
That step is only updating the archive on the release, it is not walking the tag to HEAD.

I also find "latest" tag to be confusing since Github also labels a release as "latest".
So, I resolved both of these issues in [another collection](https://github.com/cognifloyd/st2_installer.ansible/blob/63a1611f3dbff71038f25aae3dc04435379d0aa6/.github/workflows/rebuild-tip-collection.yaml#L42-L59) I'm working on like this:
```
      # Moving the tag leaves an orphan artifact. Just changing the artifact doesn't move the tag.
      - name: Delete tip tag and release (so that it matches the tip of main)
        uses: dev-drprasad/delete-tag-and-release@v0.1.2
        with:
          delete_release: true
          tag_name: tip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update tip release tag with new artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.repository_owner }}-st2_installer-tip.tar.gz
          asset_name: ${{ github.repository_owner }}-st2_installer-tip.tar.gz
          body: "This is a development release of the tip (head) of the main branch."
          tag: tip
          overwrite: true
```
