### ISSUE TITLE
Unable to authenticate with MongoDB: check_compatibility() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by NoxInmortus** [ansible-collections/community.mongodb#230]
##### SUMMARY
The mongodb_replicaset module return an error :
`Unable to authenticate with MongoDB: check_compatibility() takes 2 positional arguments but 3 were given`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mongodb_replicaset

##### ANSIBLE VERSION
```
2.9.14
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/tmp/test/ansible.cfg) = True
CACHE_PLUGIN(/tmp/test/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/tmp/test/ansible.cfg) = $HOME/.ansible/tmp/cache
CACHE_PLUGIN_TIMEOUT(/tmp/test/ansible.cfg) = 86400
DEFAULT_ACTION_PLUGIN_PATH(/tmp/test/ansible.cfg) = ['/usr/share/ansible_plugins/action_plugins']
DEFAULT_BECOME(/tmp/test/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/tmp/test/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/tmp/test/ansible.cfg) = root
DEFAULT_CALLBACK_PLUGIN_PATH(/tmp/test/ansible.cfg) = ['/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH(/tmp/test/ansible.cfg) = ['/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/tmp/test/ansible.cfg) = ['/usr/share/ansible_plugins/filter_plugins']
DEFAULT_FORKS(/tmp/test/ansible.cfg) = 20
DEFAULT_GATHERING(/tmp/test/ansible.cfg) = smart
DEFAULT_HOST_LIST(/tmp/test/ansible.cfg) = ['/tmp/test/hosts']
DEFAULT_LOOKUP_PLUGIN_PATH(/tmp/test/ansible.cfg) = ['/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/tmp/test/ansible.cfg) = Ansible managed: {file} modified by {uid}
DEFAULT_MODULE_NAME(/tmp/test/ansible.cfg) = shell
DEFAULT_POLL_INTERVAL(/tmp/test/ansible.cfg) = 10
DEFAULT_ROLES_PATH(/tmp/test/ansible.cfg) = ['/tmp/test/roles']
DEFAULT_STRATEGY(/tmp/test/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/tmp/test/ansible.cfg) = ['/opt/mitogen-0.2.9/ansible_mitogen/plugins/strategy']
DEFAULT_TIMEOUT(/tmp/test/ansible.cfg) = 10
DEFAULT_TRANSPORT(/tmp/test/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/tmp/test/ansible.cfg) = ['/usr/share/ansible_plugins/vars_plugins']
DEFAULT_VAULT_PASSWORD_FILE(/tmp/test/ansible.cfg) = /tmp/test/vault.sh
DEPRECATION_WARNINGS(/tmp/test/ansible.cfg) = False
INTERPRETER_PYTHON(/tmp/test/ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/tmp/test/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Orchestrator : Debian 10 64 bits / Python 3.8.5
Hosts: Debian 10 64 bits / Python 3.5.3

##### STEPS TO REPRODUCE
I wrote a task to initiate replicaset :

```
- name: Initiate replicaSet
  mongodb_replicaset:
    login_host: localhost
    login_user: root
    login_port: '{{ mongodb_port|default(omit) }}'
    login_password: '{{ mongodb_root_password|default(omit) }}'
    chaining_allowed: '{{ mongodb_replicaset.chaining_allowed|default(omit) }}'
    election_timeout_millis: '{{ mongodb_replicaset.election_timeout_millis|default(omit) }}'
    heartbeat_timeout_secs: '{{ mongodb_replicaset.heartbeat_timeout_secs|default(omit) }}'
    replica_set: '{{ mongodb_replicaset.name }}'
    arbiter_at_index: '{{ mongodb_replicaset.arbiter_at_index|default(omit) }}'
    members: "[{{ mongodb_replicaset.members|join(',') }}]"
    members: collab
    ssl: '{{ mongodb_replicaset.ssl|default(omit) }}'
    ssl_cert_reqs: "{{ mongodb_replicaset.ssl_cert_reqs|default('CERT_OPTIONAL') }}"
    validate: '{{ mongodb_replicaset.validate|default(omit) }}'
```

These are my vars :
```
mongodb_root_password: 'test'
mongodb_replicaset:
  name: 'rs0'
  members:
    - test:27017
  validate: 'false'
```

I previously created a single mongodb node with a root user (with test pwd) on the admin db. I can log in fine.
here is the /etc/mongod.conf
```
storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
systemLog:
  destination: syslog
net:
  port: 27017
  bindIp: 0.0.0.0
processManagement:
  timeZoneInfo: /usr/share/zoneinfo
cloud:
 monitoring:
    free:
       state: off
replication:
  replSetName: rs0
  enableMajorityReadConcern: true
security:
  authorization: enabled
  keyFile: /etc/mongodb-keyfile
```

##### EXPECTED RESULTS
Module works and initiate replicaset.

##### ACTUAL RESULTS
error:
```
Unable to authenticate with MongoDB: check_compatibility() takes 2 positional arguments but 3 were given
```
