### ISSUE TITLE
Add idempotency feature to mongodb_shell module

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.mongodb#257]
#### SUMMARY

Would be good to support idempotency  in the mongodb_shell module. Due to the nature of the module we won't be able to support true idempotency but we can fake it. For example I often achieve this in the shell module with something like the following....

```
- name: Run configdb_admin.js file via the cmd line
  shell: mongo admin --host cfg/localhost:27019 --username {{ admin_user }} --password {{ admin_user_password }} configdb_admin.js && touch configdb_admin.success
  args:
    creates: configdb_admin.success
  when: ansible_hostname == "mongos1"
```

The module could create a <filename>.success file for each js command file that is successfully executed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mongodb_shell
