### ISSUE TITLE
mongodb_status fails due to "Even number of servers currently in replicaset"

### ISSUE THREAD

**Issue by tetianakravchenko** [ansible-collections/community.mongodb#302]
##### SUMMARY
For the mongodb setup: primary - secondary - secondary - hidden secondary (initiated with `validate: no` setting)
`community.mongodb.mongodb_status` fails with the error:
```
FAILED! => {"changed": false, "msg": "Even number of servers currently in replicaset."}
```
due to: https://github.com/ansible-collections/community.mongodb/blob/master/plugins/modules/mongodb_status.py#L159-L184

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.mongodb.mongodb_status`

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
```

##### CONFIGURATION

```paste below
-
```

##### STEPS TO REPRODUCE

- initiate replicaset with 4 members, 1 of each has `hidden: true, priority: 0, votes: 0`

```yaml
- name: Ensure replicaset exists
  community.mongodb.mongodb_replicaset:
    replica_set: "rs0"
    members:
    - host: "test-0:27017"
    - host: "test-1:27017"
    - host: "test-2:27017"
    - host: "test-hidden:27017"
      hidden: true
      priority: 0
      votes: 0
    validate: no
- name: check replicaset {{replicaset_id_override}} status
  community.mongodb.mongodb_status:
    replica_set: "rs0"
    login_user: "{{ mongodb_admin_name }}"
    login_password: "{{ mongodb_admin_password }}"
  register: rs_status
  ignore_errors: yes
```

##### EXPECTED RESULTS

To not have this validation at this step, or have option to disable it, the same as done for `community.mongodb.mongodb_replicaset`

##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "msg": "Even number of servers currently in replicaset."}
```

```paste below

```

**Comment by rhysmeister** [comment]
Hello @tetianakravchenko 

Thanks for your report. I've merged a fix in https://github.com/ansible-collections/community.mongodb/pull/303 that fixes this. You can pickup the latest build from https://github.com/ansible-collections/community.mongodb/releases/tag/latest

Cheers,

Rhys

**Comment by rhysmeister** [comment]
This change requires auth now and breaks a few things elsewhere. I'll rethink this.

**Comment by rhysmeister** [comment]
Done. Use the module as before and it behaves as it always did.

Specify a validate value of "votes". Ensure votes are odd, one PRIMARY and only valid states in replicaset. Auth is required here due to the use of the replSetGetConfig cmd.

```
  community.mongodb.mongodb_status:
    login_host: localhost
    login_port: 3001
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ mongodb_admin_password }}"
    replica_set: "{{ current_replicaset }}"
    validate: "votes"
```

Specify a value of "minimal" and we check only that 1 primary exists in the rs and the other members are in a valid state.

```
  community.mongodb.mongodb_status:
    login_host: localhost
    login_port: 3001
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ mongodb_admin_password }}"
    replica_set: "{{ current_replicaset }}"
    validate: "minimal"
```
