### ISSUE TITLE
Inconsistent port usage

### ISSUE THREAD

**Issue by maxolasersquad** [ansible-collections/community.mongodb#311]
##### SUMMARY
The mongodb_config role sets the port for mongodb to listen on to 27019. However, the mongodb_auth role defaults to using port 27017. This inconsistency means that using this collection one must override the `config_port` variable for at least one of these roles.

##### ISSUE TYPE 
- Bug Report

##### COMPONENT NAME
community.mongodb

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/david/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/david/code/deployment/ansible.cfg) = ['/home/david/code/deployment/hosts']
```

##### OS / ENVIRONMENT
Ubuntu 20.04

##### STEPS TO REPRODUCE

```yaml
---
- hosts: mongo_db
  become: yes
  roles:
    - role: community.mongodb.mongodb_repository
      mongodb_version: "4.4"
    - role: community.mongodb.mongodb_install
    - role: community.mongodb.mongodb_linux
    - role: community.mongodb.mongodb_config
      mongodb_admin_password: foo
      mongodb_users:
        - database: bar
          user: bar
          password: foobar
```

##### EXPECTED RESULTS
I expect that MongoDB will be installed, configured, and users created.

##### ACTUAL RESULTS
The user cannot be created because the ports do not match across roles by default.

```paste below
 -------------------------------------------------------------
/ TASK [community.mongodb.mongodb_auth : Add mongo admin user \
\ with localhost exception]                                   /
 -------------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
fatal: [dev-database.dev-bi.com]: FAILED! => {"changed": false, "msg": "Unable to add or update user: localhost:27017: [Errno 111] Connection refused"}
```
