### ISSUE TITLE
stepdown fails on primary node with "there are no users authenticated" error

### ISSUE THREAD

**Issue by janbaer** [ansible-collections/community.mongodb#314]
##### SUMMARY
I'm trying to run **stepdown** task on the primary node of a replicaset, but I just get the error

```
unable to connect to database: there are no users authenticated
```
When i run the **shutdown** task with the same parameters, it works  fine, so the credentials seems the be fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- mongodb_stepdown

##### ANSIBLE VERSION

```
ansible 2.10.6
  config file = /home/jan/Projects/check24/bu/infrastructure/provisioning/ansible.cfg
  configured module search path = ['/home/jan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
```

##### CONFIGURATION

```
ANSIBLE_SSH_CONTROL_PATH(/home/jan/Projects/check24/bu/infrastructure/provisioning/ansible.cfg) = %(directory)s/%%h-%%p-%%r
DEFAULT_VAULT_PASSWORD_FILE(/home/jan/Projects/check24/bu/infrastructure/provisioning/ansible.cfg) = /home/jan/Projects/check24/bu/infrastructure/ansible/.secrets/vault/.vault_password_file
```

##### OS / ENVIRONMENT
```
Linux JABASOFT-LINUX-PC1 5.4.101-1-MANJARO #1 SMP PREEMPT Fri Feb 26 11:18:55 UTC 2021 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS
Should work in the same way as **shutdown** is working

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pymongo.errors.OperationFailure: there are no users authenticated, full error: {'operationTime': Timestamp(1615916515, 1), 'ok': 0.0, 'errmsg': 'there are no users authenticated', 'code': 13, 'codeName': 'Unauthorized', '$clusterTime': {'clusterTime': Timestamp(1615916515, 1), 'signature': {'hash': b'\x10\xd5\x99o\x8e\xf1\xd4\xd7A\x8f\x05\xd7k`\x92_\xed\xfc\x90\x8b', 'keyId': 6905267239608385537}}}
fatal: [bu-stg-mongo-01.**]: FAILED! => {"changed": false, "msg": "unable to connect to database: there are no users authenticated, full error: {'operationTime': Timestamp(1615916515, 1), 'ok': 0.0, 'errmsg': 'there are no users authenticated', 'code': 13, 'codeName': 'Unauthorized', '$clusterTime': {'clusterTime': Timestamp(1615916515, 1), 'signature': {'hash': b'\\x10\\xd5\\x99o\\x8e\\xf1\\xd4\\xd7A\\x8f\\x05\\xd7k`\\x92_\\xed\\xfc\\x90\\x8b', 'keyId': 6905267239608385537}}}"}
```

**Comment by rhysmeister** [comment]
Hello @janbaer,

Could you please provide the Ansible for both tasks (stepdown and shutdown).

Thanks,

Rhys

**Comment by janbaer** [comment]
```yaml
- name: "Stepdown primary server on {{ host_name }}"
  community.mongodb.mongodb_stepdown:
    login_database: "admin"
    login_host: "{{ ansible_host }}"
    login_port: 27017
    login_user: "administrator"
    login_password: "{{ mongodb_admin_pass }}"
    stepdown_seconds: 60
  when: "mongodb_master is defined and mongodb_master == true"

- name: "Shutdown mongo server on {{ host_name }}"
  community.mongodb.mongodb_shutdown:
    login_database: "admin"
    login_host: "{{ ansible_host }}"
    login_port: 27017
    login_user: "administrator"
    login_password: "{{ mongodb_admin_pass }}"
  when: "mongodb_master is defined"
```
