### ISSUE TITLE
Once the authorization is set cannot reuse the mongodb_auth role

### ISSUE THREAD

**Issue by sedhupathygit** [ansible-collections/community.mongodb#391]
##### SUMMARY
Once the authorization is set cannot reuse the mongodb_auth role

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mongodb_auth role

##### ANSIBLE VERSION
ansible [core 2.11.2] 
  config file = /home/dell/rall/infra-ansible/ansible.cfg
  configured module search path = ['/home/dell/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dell/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/dell/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/dell/.local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 3.0.1
  libyaml = True

```


##### STEPS TO REPRODUCE
have to add login_user and login_password vars for - name: Add mongo admin user with localhost exception play in community.mongodb/roles/mongodb_auth/tasks/main.yml



##### ACTUAL RESULTS
"unable to connect to database: command listDatabases requires authentication, full error: {'operationTime': Timestamp(1632984209, 2), 'ok': 0.0, 'errmsg': 'command listDatabases requires authentication', 'code': 13, 'codeName': 'Unauthorized', '$clusterTime': {'clusterTime': Timestamp(1632984209, 2),}}"

```

**Comment by rhysmeister** [comment]
Hello @sedhupathygit,

The role assumes that it's only being used for initial deployment but what you want could probably be quite easily implemented. 

Only the last task needs to be run...

```
- name: Add additional mongo users
  include_tasks: mongodb_auth_user.yml
  loop: "{{ mongodb_users }}"
  loop_control:
    loop_var: _mongodb_user
  # using loop_control: label does not obscure the password in output for verbosity > 1
  # So, loop over an include where the task name will include the username + db, but the loop var won't print out.
  no_log: yes
```

Could probably be done with a block and variable to control which tasks are executed.
