### ISSUE TITLE
MongoDB shell module ignores 'db' parameter in combination with the 'file' parameter

### ISSUE THREAD

**Issue by ManuelSchmitzberger** [ansible-collections/community.mongodb#408]
##### SUMMARY
Using the 'db' parameter is ignored in combination with the 'file' parameter and using the default value for the 'db' parameter. Running the module with the 'eval' parameter works though.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mongodb_shell

##### ANSIBLE VERSION
```paste below
ansible [core 2.11.5] 
  python version = 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
  jinja version = 3.0.2
  libyaml = True

```

##### COLLECTION VERSION
```paste below
Collection        Version
----------------- -------
community.general 3.7.0
community.mongodb 1.3.1
```

##### CONFIGURATION
```paste below
```

##### OS / ENVIRONMENT

```
OS: Arch Linux x86_64 
Kernel: 5.14.11-arch1-1
CPU: Intel i7-8565U (8) @ 4.600GHz 
GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620]
```

##### STEPS TO REPRODUCE

Running the following will create a `test` database instead of a `tux` database:

```yaml
- name: Run 'tux' script
  community.mongodb.mongodb_shell:
    db: tux
    login_user: admin
    login_password: admin
    file: /etc/mongodb-scripts/tux.js
    idempotent: no
```

The `tux.js` includes the following commands:
```
db.createCollection("tux0")
db.createCollection("tux1")
```

##### EXPECTED RESULTS

It creates a `tux` DB instead of the `test` DB.

##### ACTUAL RESULTS

```paste below
```
