### ISSUE TITLE
Add arbiter only node to mongodb_replicaset module 

### ISSUE THREAD

**Issue by tabbi** [ansible-collections/community.mongodb#409]
SUMMARY

Good day! how about adding replica set initialization with 1 participant as arbiter to the community.mongodb.mongodb_replicaset module? in the documentation for the module, I did not find how to do it

**Comment by tabbi** [comment]
@rhysmeister wow! thanks a lot!     arbiter_at_index: 2 meaning that arbiter will be node which id is 2? 
mongodb1 - id 0
mongodb2 -id 1
mongod3 - id 2

**Comment by rhysmeister** [comment]
Exactly.

Rhys

**Comment by rhysmeister** [comment]
https://github.com/ansible-collections/community.mongodb/pull/411

**Comment by tarek1375** [comment]
Hi,
I tried to reuse the exemple:
```
- name: Replicaset with one arbiter node
  community.mongodb.mongodb_replicaset:
    login_host: localhost
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ _mongodb_admin_password }}"
    replica_set: rs0
    ssl_keyfile: mongod.key
    reconfigure: true
    arbiter_at_index: 2
    members:
      - rs1-mongo-prod:27017
      - rs2-mongo-prod:27017
      - rs0-mongo-prod:27017
  when: groups.mongodb.index(inventory_hostname) == 0
```
And when i check my primary, i get the (P-S-S) architecture.
```
rs0:SECONDARY> rs.config()
{
	"_id" : "rs0",
	"version" : 5,
	"term" : 5,
	"protocolVersion" : NumberLong(1),
	"writeConcernMajorityJournalDefault" : true,
	"members" : [
		{
			"_id" : 1,
			"host" : "rs1-mongo-prod:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		},
		{
			"_id" : 2,
			"host" : "rs2-mongo-prod:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		},
		{
			"_id" : 3,
			"host" : "rs0-mongo-prod:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		}
	],
```
If anyone could help, i don't really understand why.
