### ISSUE TITLE
mongodb_user module fails

### ISSUE THREAD

**Issue by sergesal** [ansible-collections/community.mongodb#421]
##### SUMMARY

Module is crashing if a user does not exist yet.
The next issue is that you must provide a password for a new user. Users created in $external db can not have a password, only a certificate. If you omit the password then the module fails.
The next issue is that this new user needs to be created in $external db and if you change database from admin to $external then it fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mongodb_user.py
mongodb_common.py
##### ANSIBLE VERSION

```paste below
ansible [core 2.11.5] 

```

##### COLLECTION VERSION

```paste below
community-mongodb-1.3.2
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL 8

##### STEPS TO REPRODUCE

```yaml
- name: Adding superuser
  mongodb_user:
    login_host: 127.0.0.1
    login_port: "{{ mongo_port }}"
    login_database: "$external"
    database: "$external"
    create_for_localhost_exception: "{{ (mongo_directory + '/super_usr') if mongo_connect_status.rc != 0 else omit }}"
    update_password: on_create
    name: "CN=127.0.0.1,OU=super,O=<name>,L=<name>,ST=<name>,C=US"
    roles:
      - db: admin
        role: userAdminAnyDatabase
    ssl: true
    ssl_ca_certs: "{{ mongo_ca_crt }}"
    ssl_certfile: "{{ mongo_super_pem }}"
    auth_mechanism: "{{ 'MONGODB-X509' if mongo_connect_status.rc == 0 else omit }}"
    state: present
    connection_options:
      - "tlsAllowInvalidHostnames=true"

```

##### EXPECTED RESULTS

The user is created

##### ACTUAL RESULTS

fatal: [sds01]: FAILED! => changed=false 
  msg: 'Unable to add or update user: not authorized on $external to execute command { usersInfo: 1, lsid: { id: UUID("312570d9-a610-49d9-b97a-6da8dec3c6a7") }, $db: "$external", $readPreference: { mode: "primaryPreferred" } }, full error: {''ok'': 0.0, ''errmsg'': ''not authorized on $external to execute command { usersInfo: 1, lsid: { id: UUID("312570d9-a610-49d9-b97a-6da8dec3c6a7") }, $db: "$external", $readPreference: { mode: "primaryPreferred" } }'', ''code'': 13, ''codeName'': ''Unauthorized''}'      

```paste below
Created these patches to workaround this issue for now

--- /usr/share/ansible/collections/ansible_collections/community/mongodb/plugins/modules/mongodb_user.py        2021-12-06 10:13:54.810538051 +0000
+++ mongodb_user.py.patch       2021-12-07 13:50:53.557334766 +0000
@@ -241,7 +241,7 @@
         # when auth is enabled on a new instance. The loalhost exception should
         # allow us to create the first user. If the localhost exception does not apply,
         # then user creation will also fail with unauthorized. So, ignore Unauthorized here.
-        if hasattr(excep, 'code') and excep.code == 13:  # 13=Unauthorized
+        if hasattr(excep, 'code') and excep.code in [11, 13]:  # 13=Unauthorized, 11=UserNotFound
             exists = False
         else:
             raise
@@ -384,7 +384,15 @@

         try:
             if update_password != 'always':
-                uinfo = user_find(client, user, db_name)
+                try:
+                    uinfo = user_find(client, user, db_name)
+                except Exception as e:
+                    # This is a workaround to avoid crashing if the user does not exist yet
+                    if db_name == "$external":
+                        uinfo = None
+                    else:
+                        raise Exception(e)
+
                 if uinfo:
                     password = None
                     if not check_if_roles_changed(uinfo, roles, db_name):

and
--- /usr/share/ansible/collections/ansible_collections/community/mongodb/plugins/module_utils/mongodb_common.py 2021-12-06 10:13:54.823538050 +0000
+++ mongodb_common.py.patch     2021-12-07 13:50:53.541334775 +0000
@@ -268,9 +268,6 @@
             # Get server version:
             srv_version = check_srv_version(module, client)
             check_driver_compatibility(module, client, srv_version)
-        elif LooseVersion(PyMongoVersion) >= LooseVersion('3.0'):
-            if module.params['database'] != "admin":
-                module.fail_json(msg='The localhost login exception only allows the first admin account to be created')
             # else: this has to be the first admin user added
     return client


```

**Comment by rhysmeister** [comment]
Hello @sergesal ,

Thanks for the report. The functionality for X509 was implemented according to a specific user request...

https://github.com/ansible-collections/community.mongodb/pull/212

Your use case is slightly different so officially it's not supported. If you want this to be supported I'd need a test env provided from you that I can setup in our CI. I'm pretty sure you patches would break other use cases too so that would need a rethink.

Also: What version of MongoDB is this running under?

Cheers,

Rhys

**Comment by sergesal** [comment]
Hello @rhysmeister ,

Thank you for a quick response.
The MongoDB version is

MongoDB shell version v4.4.1
Build Info: {
    "version": "4.4.1",
    "gitVersion": "ad91a93a5a31e175f5cbf8c69561e788bbc55ce1",
    "openSSLVersion": "OpenSSL 1.1.1g FIPS  21 Apr 2020",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "rhel80",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}

**Comment by rhysmeister** [comment]
No further feedback so closing this. If you want this use case support we need a test env to validate this against, i.e. docker / k8.

**Comment by sergesal** [comment]
The steps to reproduce this are straight forward. Just need to create some certificates and made some changes to mongod.conf and then just run the playbook with the mongodb_user module above

'''
mkdir -p /mongo/certs
cd /mongo/certs

prefix="/C=US/ST=YourState/L=YourCity/O=YourCompany"

#-----------------------------------------------------------
# Generate self signed root CA cert
#-----------------------------------------------------------
openssl req -days 3650 -nodes -x509 -newkey rsa:2048 -keyout ca.key -out ca.crt -subj "${prefix}/CN=ROOTCA"

###MAKE SUPER User

username="super"

#-----------------------------------------------------------
# Generate client cert to be signed
#-----------------------------------------------------------
openssl req -days 3650 -nodes -newkey rsa:2048 -keyout ${username}.key -out ${username}.csr -subj "${prefix}/OU=${username}/CN=127.0.0.1"

#-----------------------------------------------------------
# Sign the client cert
#-----------------------------------------------------------
openssl x509 -req -days 3650 -in ${username}.csr -CA ca.crt -CAkey ca.key -CAserial ca.srl -out ${username}.crt

#-----------------------------------------------------------
# Create client PEM file
#-----------------------------------------------------------
cat ${username}.key ${username}.crt > ${username}.pem

'''

In mongod.conf need to enable security
'''
setParameter:
 authenticationMechanisms: MONGODB-X509
 # This only allows auth bypass to be used for the first user that is created, after which it does not do anything.
 enableLocalhostAuthBypass: 1
 
security:
 clusterAuthMode: x509
 authorization: enabled
 javascriptEnabled: false

'''

**Comment by rhysmeister** [comment]
Please also supply an auth example with the mongo cmd that can be used as a reference.

**Comment by jnm27** [comment]
Yes, check https://docs.mongodb.com/manual/reference/method/db.createUser/ documentation. That is used for external credentials

**Comment by sergesal** [comment]
Yes, the users we create are in the $external db and they can not have a password, only a certificate.
```
==>mongo --ssl --sslPEMKeyFile /mongo/certs/super.pem --sslCAFile /mongo/certs/ca.crt 127.0.0.1:28253 /usr/local/tfdm/cred.js 
MongoDB shell version v4.4.1
connecting to: mongodb://127.0.0.1:28253/test?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("74dae1c1-f4fb-44f5-b515-f4dc0b60b314") }
MongoDB server version: 4.4.1
Successfully added user: {
        "user" : "CN=127.0.0.1,OU=super,O=YourCompany,L=YourCity,ST=YourState,C=US",
        "roles" : [
                {
                        "role" : "userAdminAnyDatabase",
                        "db" : "admin"
                }
        ]
}


==>mongo --ssl --sslPEMKeyFile /mongo/certs/super.pem --sslCAFile /mongo/certs/ca.crt 127.0.0.1:28253
> db.getSiblingDB("$external").getUsers()
[
        {
                "_id" : "$external.CN=127.0.0.1,OU=super,O=YourCompany,L=YourCity,ST=YourState,C=US",
                "userId" : UUID("68e4128a-2df1-4331-8316-f963eaef3de6"),
                "user" : "CN=127.0.0.1,OU=super,O=YourCompany,L=YourCity,ST=YourState,C=US",
                "db" : "$external",
                "roles" : [
                        {
                                "role" : "userAdminAnyDatabase",
                                "db" : "admin"
                        }
                ],
                "mechanisms" : [
                        "external"
                ]
        }
]
> 

==>cat cred.js 
db = db.getSiblingDB('\$external');

/* Create super */
db.createUser(
  {
    user: "CN=127.0.0.1,OU=super,O=YourCompany,L=YourCity,ST=YourState,C=US",
    roles: [
       { role: "userAdminAnyDatabase",   db: "admin" }
           ]
  }
)

```

**Comment by rhysmeister** [comment]
@sergesal @jnm27 OK. Assuming I can get that working easily I'll look at this after the pymongo 4 migration is done.

**Comment by rhysmeister** [comment]
@sergesal @jnm27 

We issues encountered here. Had to generate the CAserial file as that was missing. Did this with...

`echo -n '00' > ca.srl 
`

Seems happy with that but the module then thwos an SSL erorr...

`SSL handshake failed: 127.0.0.1:3001: [Errno 0] Error.`

Can you provide the exact SSL/TLS parameters you use to start the mongod process in the above example?

Rhys

**Comment by sergesal** [comment]
@rhysmeister 

Can just use -CAcreateserial parameter if there's no CAserial file, so it will create it for you.

The commands to start mongod process
```
==>mongo --ssl --sslPEMKeyFile /mongo/certs/super.pem --sslCAFile /mongo/certs/ca.crt 127.0.0.1:28253
and then to login
db.getSiblingDB("$external").auth({user:"CN=127.0.0.1,OU=super,O=YourCompany,L=YourCity>,ST=YourState,C=US",mechanism:"MONGODB-X509"}) 

```

**Comment by rhysmeister** [comment]
@sergesal,

The mongod process options are also needed. You've provided client connection params.


Rhys

**Comment by sergesal** [comment]
@rhysmeister 

The partial content of the /etc/mongod.conf is above, or you need something else?
```
TFDM==>ps -ef | grep mongo
mongo       2861       1  0 Jan22 ?        00:10:37 /usr/local/bin/mongod --config /etc/mongod.conf

```

**Comment by rhysmeister** [comment]
Everything is best

**Comment by sergesal** [comment]
Here's the /etc/mongod.conf

```
==>cat /etc/mongod.conf 
# mongod.conf
# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/
# DO NOT USE TABS

#where to log
systemLog:
 destination: file
 logAppend: true
 logRotate: reopen
 path: /data/mongo/db/mongod.log
 verbosity: 0
 quiet: false

# fork and run in background
processManagement:
 fork: true
 pidFilePath: /data/mongo/db/mongod.pid # location of pidfile

net:
 bindIp: 127.0.0.1 # Listen to local interface only, comment to listen on all interfaces.
 port: 28253
 wireObjectCheck: false
 maxIncomingConnections: 1000000
 tls:
  mode: requireTLS
  certificateKeyFile: /mongo/certs/server.pem
  CAFile: /mongo/certs/ca.crt
  FIPSMode: true

setParameter:
 authenticationMechanisms: MONGODB-X509
 # This only allows auth bypass to be used for the first user that is created, after which it does not do anything.
 enableLocalhostAuthBypass: 1
 # Needed for long queries on pages such as thread processing report.
 cursorTimeoutMillis: 18000000

security:
 clusterAuthMode: x509
 authorization: enabled
 javascriptEnabled: false

storage:
 dbPath: /data/mongo/db/
 journal:
  enabled: true
 # Store each database in its own directory
 directoryPerDB: true
 wiredTiger:
  collectionConfig:
   blockCompressor: zlib

```
