### ISSUE TITLE
Authenticate method deprecated on version 3.6 and upper

### ISSUE THREAD

**Issue by detobel36** [ansible-collections/community.mongodb#423]
##### SUMMARY

Error when running `mongodb_stepdown`. Linked (I think) to version of pymongo and mongodb.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.mongodb.mongodb_stepdown`

##### ANSIBLE VERSION

```
ansible [core 2.11.6]
  config file = /home/rdetobel/dev/m3/m3-deployer/ansible.cfg
  configured module search path = ['/home/rdetobel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/macq/m3/deployer/venv/lib/python3.6/site-packages/ansible
  ansible collection location = /home/rdetobel/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/lib/macq/m3/deployer/venv/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.3
  libyaml = True 
```

##### COLLECTION VERSION

```paste below
# /usr/lib/macq/m3/deployer/venv/lib/python3.6/site-packages/ansible_collections
Collection        Version
----------------- -------
community.mongodb 1.3.1
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = True
DEFAULT_GATHERING(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = explicit
DEFAULT_LOG_PATH(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = /home/rdetobel/dev/m3/m3-deployer/logs
DEFAULT_STDOUT_CALLBACK(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = skippy
DISPLAY_SKIPPED_HOSTS(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = False
HOST_KEY_CHECKING(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = False
INTERPRETER_PYTHON(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT

OS: Centos 7

##### STEPS TO REPRODUCE

```yaml
- name: Step down server in case it's already running and PRIMARY
  community.mongodb.mongodb_stepdown:
    login_host: localhost
    login_user: "{{ mongo_admin_user }}"
    login_password: "{{ mongo_admin_pwd }}"
    login_port: "{{ mongoc_port }}"
    login_database: "{{ mongo_admin_db }}"
    stepdown_seconds: 20
    force: yes
  ignore_errors: yes
```

Mongodb version: 3.6.15
Pymongo version: 4.0.1

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_community.mongodb.mongodb_stepdown_payload_2zqaisd3/ansible_community.mongodb.mongodb_stepdown_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_stepdown.py", line 291, in main
  File "/usr/local/lib64/python3.6/site-packages/pymongo/database.py", line 598, in command
    codec_options, session=session, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/database.py", line 504, in _command
    client=self.__client)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/pool.py", line 730, in command
    exhaust_allowed=exhaust_allowed)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/network.py", line 160, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/helpers.py", line 170, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: there are no users authenticated, full error: {'operationTime': Timestamp(1641394220, 2), 'ok': 0.0, 'errmsg': 'there are no users authenticated', 'code': 13, 'codeName': 'Unauthorized', '$gleStats': {'lastOpTime': Timestamp(0, 0), 'electionId': ObjectId('7fffffff000000000000000e')}, '$clusterTime': {'clusterTime': Timestamp(1641394220, 2), 'signature': {'hash': b'\xb0\xda\xf2E\xa8\x1a\x1b3\xc8\xb0\x10W\x07\xd4\xcdMH^\x08\\', 'keyId': 7041187058852823046}}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_community.mongodb.mongodb_stepdown_payload_2zqaisd3/ansible_community.mongodb.mongodb_stepdown_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_stepdown.py", line 296, in main
  File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 2583, in __call__
    self.__name)
TypeError: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists.
fatal: [m3n1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_mechanism": null,
            "connection_options": null,
            "force": true,
            "interval": 30,
            "login_database": "admin",
            "login_host": "localhost",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_port": VALUE_SPECIFIED_IN_NO_LOG_PARAMETER,
            "login_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "poll": 1,
            "secondary_catch_up": 10,
            "ssl": false,
            "ssl_ca_certs": null,
            "ssl_cert_reqs": "CERT_REQUIRED",
            "ssl_certfile": null,
            "ssl_crlfile": null,
            "ssl_keyfile": null,
            "ssl_pem_passphrase": null,
            "stepdown_seconds": 20 
        }
    },
    "msg": "unable to connect to database: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists."
}
...ignoring 
```

## Personnal analysis

If I'm not wrong `authenticate` method is deprecated (and the removed): https://pymongo.readthedocs.io/en/3.6.1/api/pymongo/database.html#pymongo.database.Database.authenticate
I supposed we need to update this: https://github.com/ansible-collections/community.mongodb/blob/master/plugins/module_utils/mongodb_common.py#L255

Is it correct ?

**Comment by rhysmeister** [comment]
Hello @detobel36,

Thanks for the report. Yes, we're aware of this...

https://github.com/ansible-collections/community.mongodb/pull/418

For the immediate you can roll back to the 3.12.2 driver. I will probably rewrite the logic for this as the existing code is a bit ugly.

Regards,

Rhys

**Comment by detobel36** [comment]
Thank you for your reply (and for the trick to making it work).    

Just one more question: I install mongo and init a shard. On the first install, I don't have any user. So I can "directly" execute the `rs.initiate` command and create a user (`db.createUser(...)`).    
But when I "re"run ansible, I need to specified the user credential...    

Concretely, I have this task for the first "run":
```YAML
- name: Initialize the replica set
  community.mongodb.mongodb_shell:
    login_host: localhost
    login_port: "{{ mongoc_port }}"
    login_database: "{{ mongo_admin_db }}"
    eval: "<command>"
    idempotent: yes
```
And I must do this for the second:
```YAML
- name: Initialize the replica set
  community.mongodb.mongodb_shell:
    login_host: localhost
    login_user: "{{ mongo_admin_user }}"
    login_password: "{{ mongo_admin_pwd }}"
    login_port: "{{ mongoc_port }}"
    login_database: "{{ mongo_admin_db }}"
    eval: "<command>"
    idempotent: yes
```
Obviously if I specified the user and password for the first run, it doesn't work. Indeed, the user doesn't exist so -> error because I'm not authorised.


Do you have a solution ? Or is it also something you working on ?

**Comment by rhysmeister** [comment]
Hello @detobel36,

You want to use the mongodb_replicaset module for this. There's code to handle this case.

Cheers,

Rhys

**Comment by detobel36** [comment]
Again: thanks for your reply 😃 

I test with:
```YAML
- name: Initialize the replica set
  community.mongodb.mongodb_replicaset:
    login_host: localhost
    login_user: "{{ mongo_admin_user }}"
    login_password: "{{ mongo_admin_pwd }}"
    login_port: "{{ mongoc_port }}"
    login_database: "{{ mongo_admin_db }}"
    replica_set: "configreplica"
    members: "{{ play_hosts | product([(mongoc_port | string)]) | map('join', ':') | join(',') }}"
  when: "'mongo_primary' in group_names"
```

But I have this error:
```
TASK [mongoc : Initialize the replica set] ************************************************************************************************************************************************************************
task path: /home/rdetobel/dev/m3/m3-deployer/roles/mongoc/tasks/main.yml:87
The full traceback is:
  File "/tmp/ansible_community.mongodb.mongodb_replicaset_payload_74oahqe0/ansible_community.mongodb.mongodb_replicaset_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_replicaset.py", line 363, in main
  File "/usr/local/lib64/python3.6/site-packages/pymongo/database.py", line 1581, in authenticate
    connect=True)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/mongo_client.py", line 815, in _cache_credentials
    sock_info.authenticate(credentials)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/pool.py", line 837, in authenticate
    auth.authenticate(credentials, self)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/auth.py", line 672, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/auth.py", line 592, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
  File "/usr/local/lib64/python3.6/site-packages/pymongo/auth.py", line 295, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/pool.py", line 721, in command
    exhaust_allowed=exhaust_allowed)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/network.py", line 163, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
fatal: [m3n1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "arbiter_at_index": null,
            "auth_mechanism": null,
            "chaining_allowed": true,
            "connection_options": null,
            "election_timeout_millis": 10000,
            "heartbeat_timeout_secs": 10,
            "login_database": "admin",
            "login_host": "localhost",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_port": 27018,
            "login_user": "m3admin",
            "members": [
                "m3n1:27018",
                "m3n2:27018",
                "m3n3:27018"
            ],
            "protocol_version": 1,
            "replica_set": "configreplica",
            "ssl": false,
            "ssl_ca_certs": null,
            "ssl_cert_reqs": "CERT_REQUIRED",
            "ssl_certfile": null,
            "ssl_crlfile": null,
            "ssl_keyfile": null,
            "ssl_pem_passphrase": null,
            "validate": true
        }
    },
    "msg": "Unable to authenticate with MongoDB: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$gleStats': {'lastOpTime': Timestamp(0, 0), 'electionId': ObjectId('000000000000000000000000')}}"
} 
```

Version of community.mongodb: _1.3.1_

**Comment by rhysmeister** [comment]
Are you still using the 4.X driver?

**Comment by detobel36** [comment]
I use this version of pymongo:
```YAML
- name: Install pymongo to be able to run all ansible module
  pip:
    name: pymongo==3.12.2
```

**Comment by rhysmeister** [comment]
I would check your environment. This use case 100% works. Start with a fresh env if possible.

**Comment by detobel36** [comment]
Okay... Verry strange, I do the test on a "clean" docker install 😕 

I will made more tests...    
For remind:
- Centos 7
- mongo version 3.6.15
- python 3.6.8
- pymongo 3.12.2
- ansible core 2.11.6

I try to install mongo config server. Configuration:
```YAML
storage:
    dbPath: "{{ mongoc_data_dir }}"
    directoryPerDB: false
    journal:
        enabled: true

systemLog:
    destination: file
    path: "/var/log/mongodb/mongoc.log"
    logAppend: true
    logRotate: reopen
    timeStampFormat: iso8601-utc

processManagement:
    fork: true
    pidFilePath: /var/run/mongoc/mongoc.pid

# Bind to 127.0.0.1 only for local dev without sharding or anything like that
net:
    bindIp: 0.0.0.0
    port: {{ mongoc_port }}
    wireObjectCheck : true
    unixDomainSocket: 
        enabled : true

sharding:
    clusterRole: configsvr

replication:
    replSetName: configreplica

security:
    keyFile: {{ key_file }}

```
Where `mongoc_port = 27018`

And with bash command, I have this:
![image](https://user-images.githubusercontent.com/5373615/148519070-644e5fc7-78b9-47b4-a3a7-1cefe1dd3bba.png)
