### ISSUE TITLE
Create first user in shard

### ISSUE THREAD

**Issue by detobel36** [ansible-collections/community.mongodb#427]
##### SUMMARY

I try to create the first user of a sharded cluster but it failed when I specified the `replica_set`. And it only works for "primary" node.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.mongodb.mongodb_user`

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6]
config file = /home/rdetobel/dev/m3/m3-deployer/ansible.cfg
configured module search path = ['/home/rdetobel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/macq/m3/deployer/venv/lib/python3.6/site-packages/ansible
ansible collection location = /home/rdetobel/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/lib/macq/m3/deployer/venv/bin/ansible
python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
jinja version = 3.0.3
libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection        Version
----------------- -------
community.mongodb 1.3.2 
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = True
DEFAULT_GATHERING(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = explicit
DEFAULT_LOG_PATH(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = /home/rdetobel/dev/m3/m3-deployer/logs
DEFAULT_STDOUT_CALLBACK(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = skippy
DISPLAY_SKIPPED_HOSTS(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = False
HOST_KEY_CHECKING(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = False
INTERPRETER_PYTHON(/home/rdetobel/dev/m3/m3-deployer/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT

- OS: CentOS 7

##### STEPS TO REPRODUCE

Starting from a clean docker container. Just install mongo and setup systemd to have mongo.  Init replicaset

```yaml
- name: Initialize the replica set for mongoc
  community.mongodb.mongodb_replicaset:
    login_host: localhost
    login_user: "{{ mongo_admin_user }}"
    login_password: "{{ mongo_admin_pwd }}"
    login_port: "{{ mongoc_port }}"
    login_database: "{{ mongo_admin_db }}"
    replica_set: "configreplica"
    members: "{{ play_hosts | product([(mongoc_port | string)]) | map('join', ':') | join(',') }}"
    force: yes
```
Create user
```YAML
- name: Create admin user for mongoc
  community.mongodb.mongodb_user:
    login_host: localhost
    login_port: "{{ mongoc_port }}"
    replica_set: "configreplica"
    database: "{{ mongo_admin_db }}"
    name: "{{ mongo_admin_user }}"
    password: "{{ mongo_admin_pwd }}"
    roles: root
    state: present
    update_password: "always"
    create_for_localhost_exception: "{{ mongo_config_dir }}/mongoc_user_created"
```

##### EXPECTED RESULTS

Want to have a user "mongo_admin_user" with password "mongo_admin_pwd"

##### ACTUAL RESULTS

Error...

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_community.mongodb.mongodb_user_payload_6rbqc56u/ansible_community.mongodb.mongodb_user_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_user.py", line 396, in main
  File "/tmp/ansible_community.mongodb.mongodb_user_payload_6rbqc56u/ansible_community.mongodb.mongodb_user_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_user.py", line 261, in user_add
  File "/usr/local/lib64/python3.6/site-packages/pymongo/database.py", line 761, in command
    codec_options, session=session, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/database.py", line 652, in _command
    client=self.__client)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/pool.py", line 721, in command
    exhaust_allowed=exhaust_allowed)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/network.py", line 163, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: there are no users authenticated, full error: {'operationTime': Timestamp(1641906248, 1), 'ok': 0.0, 'errmsg': 'there are no users authenticated', 'code': 13, 'codeName': 'Unauthorized', '$gleStats': {'lastOpTime': Timestamp(0, 0), 'electionId': ObjectId('7fffffff0000000000000001')}, '$clusterTime': {'clusterTime': Timestamp(1641906248, 1), 'signature': {'hash': b'\x97\xce\x91\xfdn\x01j\x9f2{\x12/rW\x80\x0ey\x92\x9b\xa7', 'keyId': 7051932478616895515}}}
fatal: [m3n1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_mechanism": null,
            "connection_options": null,
            "create_for_localhost_exception": "/etc/macq/local/mongodb/mongoc_user_created",
            "database": "admin",
            "login_database": "admin",
            "login_host": "localhost",
            "login_password": null,
            "login_port": 27018,
            "login_user": null,
            "name": "m3admin",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "replica_set": "configreplica",
            "roles": [
                "root"
            ],
            "ssl": false,
            "ssl_ca_certs": null,
            "ssl_cert_reqs": "CERT_REQUIRED",
            "ssl_certfile": null,
            "ssl_crlfile": null,
            "ssl_keyfile": null,
            "ssl_pem_passphrase": null,
            "state": "present",
            "update_password": "always"
        }
    },
    "msg": "Unable to add or update user: there are no users authenticated, full error: {'operationTime': Timestamp(1641906248, 1), 'ok': 0.0, 'errmsg': 'there are no users authenticated', 'code': 13, 'codeName': 'Unauthorized', '$gleStats': {'lastOpTime': Timestamp(0, 0), 'electionId': ObjectId('7fffffff0000000000000001')}, '$clusterTime': {'clusterTime': Timestamp(1641906248, 1), 'signature': {'hash': b'\\x97\\xce\\x91\\xfdn\\x01j\\x9f2{\\x12/rW\\x80\\x0ey\\x92\\x9b\\xa7', 'keyId': 7051932478616895515}}}"
}
```

##### TEMPORARY SOLUTION

If I remove `replica_set`, it seems to work:
```YAML
- name: Create admin user for mongoc
  community.mongodb.mongodb_user:
    login_host: localhost
    login_port: "{{ mongoc_port }}"
    database: "{{ mongo_admin_db }}"
    name: "{{ mongo_admin_user }}"
    password: "{{ mongo_admin_pwd }}"
    roles: root
    state: present
    update_password: "always"
    create_for_localhost_exception: "{{ mongo_config_dir }}/mongoc_user_created"
```

```
changed: [m3n1] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "auth_mechanism": null,
            "connection_options": null,
            "create_for_localhost_exception": "/etc/macq/local/mongodb/mongoc_user_created",
            "database": "admin",
            "login_database": "admin",
            "login_host": "localhost",
            "login_password": null,
            "login_port": 27018,
            "login_user": null,
            "name": "m3admin",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "replica_set": null,
            "roles": [
                "root"
            ],
            "ssl": false,
            "ssl_ca_certs": null,
            "ssl_cert_reqs": "CERT_REQUIRED",
            "ssl_certfile": null,
            "ssl_crlfile": null,
            "ssl_keyfile": null,
            "ssl_pem_passphrase": null,
            "state": "present",
            "update_password": "always"
        }
    },
    "user": "m3admin"
}
```

##### Question
How do I need to use `create_for_localhost_exception` with shard cluster ?   
Indeed, I supposed the user is created on the "primary" and other nodes will "skip" the creation of this file. Is it true ? If yes, the next time I could have an error, no ?

**Comment by detobel36** [comment]
I try to find a solution with `community.mongodb.mongodb_status` to know which server is primary.     
But to do that I need to run `community.mongodb.mongodb_status` without user auth.  It will works the first "run". But if I re-run ansible I will have an error... Indeed, I need to loged-in (because now there is a configured user). So this `community.mongodb.mongodb_status` will failed 😕

**Comment by rhysmeister** [comment]
- Version of MongoDB?
- Version of PyMongo?

Please include the full playbook you are using, as a gist if it's big https://gist.github.com/.

**Comment by detobel36** [comment]
Mongo version:
```
MongoDB shell version v3.6.15
git version: 18934fb5c814e87895c5e38ae1515dd6cb4c00f7
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel70
    distarch: x86_64
    target_arch: x86_64
```

Pymongo:
```YAML
- name: Install pymongo to be able to run all ansible module
  pip:
    name: pymongo==3.12.2
```

Playbook:
```YAML
- name: Create the directory for config
  ansible.builtin.file:
    path: "{{ mongo_config_dir }}"
    state: directory
    owner: mongod
    group: mongod
    mode: "755"

- name: Create the mongo configuration server file
  ansible.builtin.template:
    src: mongoc.conf.j2
    dest: "{{ mongo_config_dir }}/mongoc.conf"
    mode: '644'
    force: yes
    owner: mongod
    group: mongod

- name: Create the mongo configuration server startup file
  ansible.builtin.template:
    src: mongoc.service.j2
    dest: /etc/systemd/system/mongoc.service
    mode: '644'
    force: yes

- name: Step down server in case it's already running and PRIMARY
  community.mongodb.mongodb_stepdown:
    login_host: localhost
    login_user: "{{ mongo_admin_user }}"
    login_password: "{{ mongo_admin_pwd }}"
    login_port: "{{ mongoc_port }}"
    login_database: "{{ mongo_admin_db }}"
    stepdown_seconds: 20
    force: yes
  ignore_errors: yes

- name: Restart mongoc
  ansible.builtin.systemd:
    name: mongoc
    state: restarted
    daemon_reload: yes
    masked: no

- name: Wait mongoc correclty start
  wait_for:
    port: "{{ mongoc_port }}"

- name: Initialize the replica set for mongoc
  community.mongodb.mongodb_replicaset:
    login_host: localhost
    login_user: "{{ mongo_admin_user }}"
    login_password: "{{ mongo_admin_pwd }}"
    login_port: "{{ mongoc_port }}"
    login_database: "{{ mongo_admin_db }}"
    replica_set: "configreplica"
    members: "{{ play_hosts | product([(mongoc_port | string)]) | map('join', ':') | join(',') }}"
    force: yes

- name: Create admin user for mongoc
  community.mongodb.mongodb_user:
    login_host: localhost
    login_port: "{{ mongoc_port }}"
    replica_set: "configreplica"
    database: "{{ mongo_admin_db }}"
    name: "{{ mongo_admin_user }}"
    password: "{{ mongo_admin_pwd }}"
    roles: root
    state: present
    update_password: "always"
    create_for_localhost_exception: "{{ mongo_config_dir }}/mongoc_user_created"
```

**Comment by rhysmeister** [comment]
- You don't need the community.mongodb.mongodb_stepdown module here.
- After the community.mongodb.mongodb_replicaset module is executed it can take the replicaset a little while to elect a primary. Use the mongodb_status module after this to ensure the replicaset has settled and elected a primary. 

Again a reminder that 3.6 is pretty old now. We no longer test against this MongoDB version.

**Comment by detobel36** [comment]
> You don't need the community.mongodb.mongodb_stepdown module here.

The goal here is to take into account the potential modification of the configuration... This `mongodb_stepdown` step is in a separate file where each seraver are "stepdown", then restart and we wait the port was open.    
But maybe you have another solution ?       
What is the link with that and the problem I exposed here ?

> After the community.mongodb.mongodb_replicaset module is executed it can take the replicaset a little while to elect a primary. Use the mongodb_status module after this to ensure the replicaset has settled and elected a primary.

As mention if I use `mongodb_status` I don't need to specified user_credential for the first run but I need to do it for the second...  So how do I do it ?

**Comment by rhysmeister** [comment]
First point - I don't know what you mean here. If you mean a reconfigure of the replicaset then I don't really see what this is here for. I think some reconfig actions will force the PRIMARY to stepdown anyway.

"As mention if I use mongodb_status I don't need to specified user_credential for the first run but I need to do it for the second... So how do I do it ?" - Most modules are build to handle this. See the following...

https://github.com/ansible-collections/community.mongodb/blob/26c77072ff10a2a396ee309928d052c142811c7a/plugins/module_utils/mongodb_common.py#L229

We use the listDatabase command to test is auth is required or not.

**Comment by detobel36** [comment]
> First point - I don't know what you mean here. If you mean a reconfigure of the replicaset then I don't really see what this is here for. I think some reconfig actions will force the PRIMARY to stepdown anyway.

No the goal is to be able to update the configuration... For instance this is a part of the config of my mongoc:
```YAML
storage:
    dbPath: "{{ mongoc_data_dir }}"
    directoryPerDB: false
    journal:
        enabled: true
```
If I change the dbPath for one specific server, I will to be able to "restart" mongo without "down time".  This is why I would like that that the node is not primary.

> EDIT I've just re-read this "then restart and we wait the port was open (and thus, this is done "host by host")." Are you running this playbook against all three hosts? You only need to run the replicaset and user modules once. There's no need to run it against all replicaset hosts if that's what you've doing here.

Right, I think I fix that after open the PR... For replicaset I use a "static" condition: `when: "'mongo_primary' in group_names"` and for use, I need to find "primary" node, thus `mongodb_status` -> `set_fact` and then a condition `when: "mongoc_primary == inventory_hostname"`


So to recap:
```YAML
- name: Create first admin user for mongoc on primary node
  community.mongodb.mongodb_user:
    login_host: localhost
    login_port: "{{ mongoc_port }}"
    login_user: "{{ mongo_admin_user }}"
    login_password: "{{ mongo_admin_pwd }}"
    login_database: "{{ mongo_admin_db }}"
    database: "{{ mongo_admin_db }}"
    name: "{{ mongo_admin_user }}"
    password: "{{ mongo_admin_pwd }}"
    update_password: always
    roles: root
    state: present
    create_for_localhost_exception: "{{ mongo_config_dir }}/mongod_user_created"
    replica_set: "{{ replica_set_name }}" # Specified the replica_set
  when: "'mongo_primary' in group_names" # Run on one server per shared
# -> Error if "mongo_primary" is not the primary node 
# (-> try to connect to other node but no user and not in local)
```

```YAML
- name: Create first admin user for mongoc on primary node
  community.mongodb.mongodb_user:
    login_host: localhost
    login_port: "{{ mongoc_port }}"
    login_user: "{{ mongo_admin_user }}"
    login_password: "{{ mongo_admin_pwd }}"
    login_database: "{{ mongo_admin_db }}"
    database: "{{ mongo_admin_db }}"
    name: "{{ mongo_admin_user }}"
    password: "{{ mongo_admin_pwd }}"
    update_password: always
    roles: root
    state: present
    create_for_localhost_exception: "{{ mongo_config_dir }}/mongod_user_created"
  when: "mongoc_primary == inventory_hostname" # To run on primary node
# -> No problem on first run
# -> Problem when second run if "primary" node is not the same -> 'mongod_user_created' doesn't exist.
```

PR #429 fix that because we try first to execute the command. If it fails, we used credentials. This way, `create_for_localhost_exception` is not necessary.

**Comment by rhysmeister** [comment]
Hi @detobel36 

The create_for_localhost_exception feature was added for a specific way of working. You can read about it in the PR...

https://github.com/ansible-collections/community.mongodb/pull/182

Typically how we worked was to have a specific host consider as a "head" host. You could do this by using a specific hostname, i.e. mongodb1, or as I do in my work, add a host variable to one of the hosts. Then you always connect to the same host when running the playbook. Yes, this breaks if the host goes away but that should be pretty unusual. Provided the replica_set parameter is provided the module will be connected to whatever the primary is anyway.

I've pointed out the examples over at https://github.com/rhysmeister/AutomatingMongoDBWithAnsible before but specifically look at....

https://github.com/rhysmeister/AutomatingMongoDBWithAnsible/blob/master/playbooks/replicaset/mongodb.yml

This example is fully idempotent. Note we specify the admin username and password for the mongodb_replicaset and mongodb_status modules before any user is created. Most of the module user code to figure out if they need to use the credentials or not. The mongodb_replicaset doesn't actually need to use the credentials until a replicaset reconfiguration is attempted. The mongodb_user module is not one of these, but you can use other methods to achieve what you want.

Cheers,

Rhys

**Comment by rhysmeister** [comment]
FYI - Wouldn't this be better for the config change?
```
- name: Create the mongo configuration server file
  ansible.builtin.template:
    src: mongoc.conf.j2
    dest: "{{ mongo_config_dir }}/mongoc.conf"
    mode: '644'
    force: yes
    owner: mongod
    group: mongod
register: config

- name: Restart mongoc
  ansible.builtin.systemd:
    name: mongoc
    state: restarted
    daemon_reload: yes
    masked: no
  when: config.changed
```

**Comment by detobel36** [comment]
The use cases that I want to complete with my playbook:
- Update mongo configuration
- Init replica set
- Update replica set
- Create first user
- Upgrade version of mongo

> The create_for_localhost_exception feature was added for a specific way of working. You can read about it in the PR...

Isn't that exactly the case we have here ?

> Typically how we worked was to have a specific host consider as a "head" host. You could do this by using a specific hostname, i.e. mongodb1, or as I do in my work, add a host variable to one of the hosts. Then you always connect to the same host when running the playbook. Yes, this breaks if the host goes away but that should be pretty unusual. Provided the replica_set parameter is provided the module will be connected to whatever the primary is anyway.

So, your playbook do:
- Init the replicaset    
  On mongodb1      
  Without login infos
- Get primary node
- Check if file `/root/mongodb_admin.success` exist
- Create user if this file doesn't exist     
  On mongodb1     
  AND     
  mongodb1 is primary
- Check if user exist and create file

But I think that with this playbook it is not possible to "update" the replica set or update the version of mongo.


> I've pointed out the examples over at https://github.com/rhysmeister/AutomatingMongoDBWithAnsible before but specifically look at....    
https://github.com/rhysmeister/AutomatingMongoDBWithAnsible/blob/master/playbooks/replicaset/mongodb.yml   
This example is fully idempotent. Note we specify the admin username and password for the mongodb_replicaset and mongodb_status modules before any user is created.

Hum, that's not what I see...   
```YAML
- name: Initialise MongoDB Replicaset
  community.mongodb.mongodb_replicaset:
    login_database: "admin"
    login_host: localhost
    members: "{{ replicaset_members | product(['.local:27017']) | map('join') | list  }}"
  register: create_rs
  when: inventory_hostname == "mongodb-1"
```


So if I recap, what I can do:
- I init the recplica set on this mongodb1
- I add the admin user on this mongodb1

So in YAML:
```YAML
- name: Initialise MongoDB Replicaset
  community.mongodb.mongodb_replicaset:
    login_database: "admin"
    login_host: localhost
    members: "{{ replicaset_members | product(['.local:27017']) | map('join') | list  }}"
  when: inventory_hostname == "mongodb1"

- name: Wait for replicaset to converge
  community.mongodb.mongodb_status:
    login_user: "{{ admin_user }}"
    login_password: "{{ admin_user_password }}"
    replica_set: rs0
    poll: 10
    interval: 10
  register: rs

- name: Lookup PRIMARY replicaset member
  set_fact:
    primary: "{{ item.key.split('.')[0] }}"
  loop: "{{ lookup('dict', rs.replicaset) }}"
  when: "'PRIMARY' in item.value"

- name: Add MongoDB Admin User using localhost exception
  community.mongodb.mongodb_user:
    name: "{{ admin_user }}"
    password: "{{ admin_user_password }}"
    database: admin
    roles:
      - "root"
    create_for_localhost_exception: "/root/mongodb_admin.success"
  when: inventory_hostname == primary
```


But if I want to add a member to the replica set it doesn't work (because I need to login).


I try to have "simple" playbook with little unnecessary operation.
