### ISSUE TITLE
ssl_cert_reqs preventing playbook to run for community.mongodb.mongodb_user task

### ISSUE THREAD

**Issue by jake-morgan** [ansible-collections/community.mongodb#444]
##### SUMMARY

When using the `mongodb.mongodb_user` task Ansible fails due to the `ssl_cert_reqs` being unknown. Removing the option, or setting the option makes no difference to the failure.

We have managed to get the `mongodb.mongodb_shell` task working using the `additional_args` parameter. But this parameter is not available for the `mongodb.mongodb_user` task (and the `ssl_cert_reqs` error would still occur regardless).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`mongodb.mongodb_user` task

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.3]
  config file = None
  configured module search path = ['/Users/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/<user>/Library/Python/3.9/lib/python/site-packages/ansible
  ansible collection location = /Users/<user>/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/<user>/Library/Python/3.9/bin/ansible
  python version = 3.9.10 (main, Jan 15 2022, 11:40:36) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /Users/<user>/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.mongodb 1.3.2

# /Users/<user>/Library/Python/3.9/lib/python/site-packages/ansible_collections
Collection        Version
----------------- -------
community.mongodb 1.3.2
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

macOS 11.6.1 running on Apple Silicon (M1)
pymongo version 4.0.2

##### STEPS TO REPRODUCE

The following playbook returns the error:

```yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a database user
      community.mongodb.mongodb_user:
        database: burgers
        name: bob
        password: 12345
        state: present
        ssl: True
        ssl_ca_certs: "/Users/<user>/rds-combined-ca-bundle.pem"
        login_user: theadmin
        login_password: password1
```

##### EXPECTED RESULTS

The user is created in mongo.

##### ACTUAL RESULTS

```paste below
PLAY [localhost] *******************************************************************************************************

TASK [Create a database user via SSL (MongoDB must be compiled with the SSL option and configured properly)] ***********
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to connect to database: Unknown option ssl_cert_reqs"}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
