### ISSUE TITLE
community.mongodb depends on old version of community.general

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.mongodb#482]
##### SUMMARY
I noticed that community.mongodb depends on community.general < 5.0.0. This basically breaks the Ansible 6 package (though not visibly to the user), since it contains both community.general 5.x.y and community.mongodb.

Please either remove the upper bound, or make sure that latest community.mongodb release always works with the latest community.general release.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
galaxy.yml

**Comment by mariolenz** [comment]
@rhysmeister You've limited `community.general` to `<5.0.0` in #477 with reference to ansible-collections/community.general#4706.

It looks like you're using some `community.general` modules in your roles, but I think you're using the FQCN so this shouldn't be a problem. Are you sure your collection doesn't run with `community.general` 5.x?

**Comment by felixfontein** [comment]
The problem is Ansible 2.9 support (ansible-base 2.10 can still use most of community.general 5.x.y). What you can do is using the extended FQCN for pam_limits (`community.general.system.pam_limits`), though that's more an implementation detail of community.general and could possibly change without advance warning. It works with Ansible 2.9 though (or at least it should - better try it out first), and for all community.general versions released so far.

**Comment by rhysmeister** [comment]
Thanks for the hints. Trying a fix in https://github.com/ansible-collections/community.mongodb/pull/483

Rhys

**Comment by felixfontein** [comment]
@rhysmeister would it be possible to have a new release where this is fixed? (The next Ansible release is in ~one week.)

**Comment by rhysmeister** [comment]
It's on my todo list. I'll try to get it done tonight.

**Comment by rhysmeister** [comment]
Done - 1.4.2

**Comment by felixfontein** [comment]
Awesome, thanks a lot!

**Comment by bluikko** [comment]
The latest community.general is flattened and there is no longer "extended FQCN" which supposedly was never supposed to be visible anywhere outside c.g anyways.

**Comment by felixfontein** [comment]
Indeed, see https://github.com/ansible-community/community-topics/issues/147, this was unfortunately forced upon us... And this is now a problem for community.mongodb since it kind of depends on it. Right now there are still redirects in place (so the workaround used in c.mongodb still works), but these are deprecated and will be removed eventually.

One workaround would be to determine which module to use depending on the Ansible/ansible-base/ansible-core version. For 2.9, the "extended FQCN" will always work, since then community.general < 5.0.0. For 2.10+, the correct (short) FQCN will always work. This can be checked with the Jinja2 expression `ansible_version.string is version('2.10', '>=')`.

Alternatively the following should work without duplicating tasks:
```yaml
- name: Set pam limits (nproc and nofile)
  action:
    # TODO: just use the `community.general.pam_limits` module once support for Ansible 2.9 is dropped
    module: "{{ 'community.general.pam_limits' if ansible_version.string is version('2.10', '>=') else 'community.general.system.pam_limits' }}
    domain: "{{ item[0] }}"
    limit_type: "{{ item[1] }}"
    limit_item: "{{ item[2] }}"
    value: "{{ item[3] }}"
  with_...: ...
```
