### ISSUE TITLE
mongodb_status fails to log in to replica set

### ISSUE THREAD

**Issue by apinter** [ansible-collections/community.mongodb#515]
##### SUMMARY

Hi,

Ran into a super weird issue today when I was rolling out OS updates. Have a playbook to update MongoDB replica set hosts in a rolling fashion. The first step the playbook makes is to collect and print the current configuration with `community.mongodb.mongodb_status` that worked today on 7 out of the 8 different replica sets I have :D 
On the faulty node it simply fails with an `Authentication Error, code 18`, which is funny because with the same user and password I can log in with `mongosh`. Was having this thought that maybe `pymongo` causing issues, but a small python script busted that theory as I was able to connect and list all databases with the same credentials. 

MongoDB version: 5.0.9 running in a pordman container
Replica set: 1 Primary, 1 Secondary, 1 Arbiter
Pymongo version: 4.3.2 (on other nodes I have various versions like 3.8 and 3.12, tried it both on these nodes sadly to no avail)

The above additional information is true for the other 7 replica sets as well, the only diff is the `pymongo` version.

##### ISSUE TYPE
- Bug Report
But maybe not.... Can't reproduce on other replica sets. 

##### COMPONENT NAME

community.mongodb.mongodb_status

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.5]
  config file = /var/home/attila.pinter/.ansible.cfg
  configured module search path = ['/var/home/attila.pinter/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/home/attila.pinter/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /var/home/attila.pinter/.ansible/collections:/usr/share/ansible/collections
  executable location = /var/home/attila.pinter/.local/bin/ansible
  python version = 3.10.7 (main, Sep  7 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /var/home/attila.pinter/.local/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.7.0  

# /var/home/attila.pinter/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.8.0  
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
CACHE_PLUGIN(/var/home/attila.pinter/.ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/var/home/attila.pinter/.ansible.cfg) = /tmp
DEFAULT_FORKS(/var/home/attila.pinter/.ansible.cfg) = 30
DEFAULT_STDOUT_CALLBACK(/var/home/attila.pinter/.ansible.cfg) = yaml
```

##### STEPS TO REPRODUCE

```yaml
- name: MongoDB rs host os upgrade
  hosts: mongod
  become: true
  gather_facts: true
  vars:
    - mongodb_username: "user"
    - mongodb_password: "password"
  tasks:
    - name: Ensure replicaset is stable before beginning
      community.mongodb.mongodb_status:
        login_user: "{{ mongodb_username }}"
        login_password: "{{ mongodb_password }}"
        login_database: "admin"
        poll: 5
        interval: 10
        replica_set: rs0
      register: rs

```

##### EXPECTED RESULTS

The plugin can connect to the replicaset and collect status information from every replica set.

##### ACTUAL RESULTS

Full verbose output is available [here](https://gist.github.com/apinter/e48ffe700d3de1cc8833a51fac7bca8e).

```
fatal: [mongo-2]: FAILED! => changed=false 
  msg: 'Unable to get MongoDB server version: Authentication failed., full error: {''ok'': 0.0, ''errmsg'': ''Authentication failed.'', ''code'': 18, ''codeName'': ''AuthenticationFailed''}'
fatal: [mongo-1]: FAILED! => changed=false 
  msg: 'Unable to get MongoDB server version: Authentication failed., full error: {''ok'': 0.0, ''errmsg'': ''Authentication failed.'', ''code'': 18, ''codeName'': ''AuthenticationFailed'', ''$clusterTime'': {''clusterTime'': Timestamp(1667464025, 1), ''signature'': {''hash'': b''\xa6\xbehPQH\x12\xa0|\xde\xf1\x1b-\x98XB\x15\x80|\xaa'', ''keyId'': 7117129412155277316}}, ''operationTime'': Timestamp(1667464025, 1)}'
```
