### ISSUE TITLE
Replicaset cannot be initialized when auth is in place

### ISSUE THREAD

**Issue by paulsjohnson91** [ansible-collections/community.mongodb#543]
##### SUMMARY
If you have a replicaset culster ready to initialise but with auth enabled and an auth user available in the admin database, the module fails with error
```
"msg": "Unable to create replica_set: Some problem command replSetInitiate requires authentication,
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.mongodb.mongodb_replicaset

##### ANSIBLE VERSION

```paste below
ansible 2.10.7
```

##### COLLECTION VERSION

```
amazon.aws        5.0.1  
ansible.netcommon 3.1.3  
ansible.posix     1.4.0  
ansible.utils     2.6.1  
community.docker  3.1.0  
community.general 5.7.0  
community.grafana 1.5.2  
community.mongodb 1.4.2  
community.mysql   3.5.1 
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Run on OSX and Linux

##### STEPS TO REPRODUCE

Basic reproduction step: set up 3 mongo nodes with auth enabled, then run replSet on the nodes.

This can be done running the example project [here](https://github.com/paulsjohnson91/mongo-docker-repo-with-auth).
In this folder run 
```
docker build . -t mongo-with-key
docker-compose -f docker-compose-auth.yaml up -d
```
You should be able to log into admin with username and password 'admin' and 'password'

```yaml
---
  - name: "Create Replicaset"
    hosts: localhost
    connection: local 
    tasks:
      - name: "create replica set"
        community.mongodb.mongodb_replicaset:
          login_host: localhost
          login_port: 27017
          login_user: admin
          login_password: password
          replica_set: rs
          members:
          - host: "mongo-0.mongo:27017"
            priority: 4
          - host: "mongo-0.mongo:27017"
            priority: 2
          - host: "mongo-0.mongo:27017"
            priority: 1
        register: rs

      - name: assertion
        assert:
          that:
            - rs.changed == True
```

##### EXPECTED RESULTS

Replica set initialised.

Note that running in mongo directly
```
config={_id:"rs",members:[{_id:0,host:"mongo-0.mongo:27017"},{_id:1,host:"mongo-1.mongo:27017"},{_id:2,host:"mongo-2.mongo:27017"},]}
```
and then either
```
db.runCommand({replSetInitiate:config})
```
or
```
rs.initiate(config)
```
runs successfully and a replicaset is initialised
##### ACTUAL RESULTS

Replicaset does not initialise as it is unauthorised.

```
The full traceback is:
  File "/var/folders/93/vbdjnj3s6mq9vjwcks1mlg700000gp/T/ansible_community.mongodb.mongodb_replicaset_payload_b5ex27dp/ansible_community.mongodb.mongodb_replicaset_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_replicaset.py", line 600, in main
  File "/var/folders/93/vbdjnj3s6mq9vjwcks1mlg700000gp/T/ansible_community.mongodb.mongodb_replicaset_payload_b5ex27dp/ansible_community.mongodb.mongodb_replicaset_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_replicaset.py", line 469, in replicaset_add
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "arbiter_at_index": null,
            "auth_mechanism": null,
            "chaining_allowed": true,
            "cluster_cmd": "hello",
            "connection_options": null,
            "debug": false,
            "election_timeout_millis": 10000,
            "force": false,
            "heartbeat_timeout_secs": 10,
            "login_database": "admin",
            "login_host": "localhost",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_port": 27017,
            "login_user": "admin",
            "max_time_ms": null,
            "members": [
                {
                    "host": "mongo-0.mongo:27017",
                    "priority": 4
                },
                {
                    "host": "mongo-0.mongo:27017",
                    "priority": 2
                },
                {
                    "host": "mongo-0.mongo:27017",
                    "priority": 1
                }
            ],
            "protocol_version": 1,
            "reconfigure": false,
            "replica_set": "rs",
            "ssl": false,
            "ssl_ca_certs": null,
            "ssl_cert_reqs": "CERT_REQUIRED",
            "ssl_certfile": null,
            "ssl_crlfile": null,
            "ssl_keyfile": null,
            "ssl_pem_passphrase": null,
            "strict_compatibility": true,
            "validate": true
        }
    },
    "msg": "Unable to create replica_set: Some problem command replSetInitiate requires authentication, full error: {'ok': 0.0, 'errmsg': 'command replSetInitiate requires authentication', 'code': 13, 'codeName': 'Unauthorized'} | OrderedDict([('_id', 'rs'), ('protocolVersion', 1), ('members', [OrderedDict([('_id', 0), ('host', 'mongo-0.mongo:27017'), ('priority', 4)]), OrderedDict([('_id', 1), ('host', 'mongo-0.mongo:27017'), ('priority', 2)]), OrderedDict([('_id', 2), ('host', 'mongo-0.mongo:27017'), ('priority', 1)])]), ('settings', {'chainingAllowed': True, 'electionTimeoutMillis': 10000})])"
}
```
