### ISSUE TITLE
mongodb_shell TLS

### ISSUE THREAD

**Issue by superset1** [ansible-collections/community.mongodb#549]
##### SUMMARY

Hello )
Connect to mongo with mongodb_shell using TLS

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

mongodb_shell

##### ADDITIONAL INFORMATION

I cant connect to create new mongo role for user when mongo uses TLS

```yaml
- name: Create Custom Backup Role 'backupCustom' When mongodb_version >= 6.0
  community.mongodb.mongodb_shell:
    login_user: "{{ mongodb_root_admin_name }}"
    login_password: "{{ mongodb_root_admin_password }}"
    login_host: "{{ groups[mongodb_main_group] | join(':' + mongodb_net_port | string + ',') + ':' + mongodb_net_port | string }}"
    login_port: "{{ mongodb_net_port }}"
    login_database: "{{ mongodb_login_database }}"
    db: "{{ mongodb_login_database }}"
    eval: "db.getRole('backupCustom') || db.createRole({role: 'backupCustom', roles: ['backup'], privileges:[{ resource: { db: 'config', collection: 'system.preimages' }, actions: [ 'find' ] }]})"
    mongo_cmd: "mongosh"
  register: _check_backupCustom_role_exists
  changed_when: _check_backupCustom_role_exists.transformed_output.operationTime is defined
  when: mongodb_major_version is version('6.0', '>=')
  tags: [mongodb, mongodb-create-admin-users]
```

**Comment by superset1** [comment]
We should use `additional_args` with `mongodb_shell` module
```
    additional_args:
      tls: ""
      tlsCertificateKeyFile: /etc/ssl/mongodb.pem
      tlsCAFile: /etc/ssl/mongodb-ca.crt
```
