### ISSUE TITLE
NTP package incorrect on RH9 and varients

### ISSUE THREAD

**Issue by alustenberg** [ansible-collections/community.mongodb#584]
##### SUMMARY

`mongodb_linux` module does not have a vars file defined for EL9

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mongodb_linux

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.5]
  python version = 3.11.3 (main, Jun 14 2023, 09:52:11) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
~ $ ansible-galaxy collection list community.mongodb

# /home/alexl/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.mongodb 1.6.1  

# /home/alexl/.pyenv/versions/3.11.3/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.mongodb 1.3.3  
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RedHat 9 / Oracle Linux 9

##### STEPS TO REPRODUCE

apply role `community.mongodb.mongodb_linux` to RH9 / OL9 / other derivative. 

##### EXPECTED RESULTS

role installs chrony as with RH8

##### ACTUAL RESULTS

```yaml
  Retrying... (1 of 6)Result was: {
    "attempts": 1,
    "changed": false,
    "failures": [
        "No package ntp available."
    ],
 [...]
    "msg": "Failed to install some of the specified packages",
    "rc": 1,
    "results": [],
    "retries": 6
}
```
