### ISSUE TITLE
Cannot create first admin user when mongodb is running in docker

### ISSUE THREAD

**Issue by pawellrus** [ansible-collections/community.mongodb#592]
##### SUMMARY

When I am trying to create first user I get an error "pymongo.errors.OperationFailure: command createUser requires authentication".
But at the same time I can succesfully add admin user via mongosh directly or via mongo_shell ansible module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mongodb_user

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.8]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/local/lib/python3.9/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.6.2 
```

##### CONFIGURATION

```paste below
[defaults]
remote_user = ansible
ansible_python_interpreter = /usr/bin/python3
ansible_artifacts_dir = /opt/ansible/artifacts
any_errors_fatal = true
inventory = inventory.ini
display_skipped_hosts = false
gathering = smart
fact_caching = jsonfile
callbacks_enabled = timer
remote_tmp = /tmp/${USER}/ansible
fact_caching_connection = /tmp/${USER}/ansible/.ansible_cache
host_key_checking=False
timeout=60
roles_path = ./roles:~/.ansible/roles
ansible_managed = This file is managed by Ansible, all changes will be lost.

[privilege_escalation]
become = True
become_method = sudo

[persistent_connection]
retries = 3
connect_timeout = 60
command_timeout = 30

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s  -o PreferredAuthentications=publickey,password -o StrictHostKeyChecking=no
pipelining = true
```

##### STEPS TO REPRODUCE

I have instance of mongodb in docker with auth enabled and replicaset rs0 initiated.

```yaml

- name: Install | Add admin user
  community.mongodb.mongodb_user:
    login_database: admin
    database: admin
    create_for_localhost_exception: /root/mongodb_admin_{{mongodb_docker_instance_name}}.success
    name: "{{ mongodb_docker_admin_user.username }}"
    password: "{{ mongodb_docker_admin_user.password }}"
    replica_set: "{{ mongodb_docker_replication_replicaset_name | default(omit) }}"
    roles:
      - dbAdminAnyDatabase
      - userAdminAnyDatabase
      - readWriteAnyDatabase
      - clusterAdmin
    login_host: localhost
    login_port: "{{ mongodb_docker_port }}"
  when: inventory_hostname == groups[mongodb_docker_replication_hosts_group][0]

```

##### EXPECTED RESULTS

I expect that first admin user succesfully created.

##### ACTUAL RESULTS

Task fail with error pymongo.errors.OperationFailure: command createUser requires authentication

```paste below
pymongo.errors.OperationFailure: command createUser requires authentication

```
