### ISSUE TITLE
Mongodb user module trouble

### ISSUE THREAD

**Issue by Chaaany** [ansible-collections/community.mongodb#618]
##### SUMMARY

When using the Mongodb user module, the template below was used and appropriate variables were added.

```
- name: Create database users
  mongodb_user:
    login_user: "{{ mongodb_root_credentials[item.instance].username }}"
    login_password: "{{ mongodb_root_credentials[item.instance].password }}"
    login_host: "{{ mongodb_endpoints[item.instance] }}"
    login_port: "{{ mongodb_ports[item.instance] }}"
    name: "{{ item.username }}"
    password: "{{ mongodb_user_credentials[item.instance][item.username] }}"
    roles: "{{ item.roles }}"
    state: "{{ item.state }}"
  with_items: "{{ mongodb_users }}"
```
Then an error message was displayed. `"unable to connect to database: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists."` 

I can't find that error message in mongodb module source code. How can I solve this problem?

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below
- ansible version: 3.3.*
```
