### ISSUE TITLE
Mongodb user module trouble

### ISSUE THREAD

**Issue by Chaaany** [ansible-collections/community.mongodb#619]
##### SUMMARY

When using the Mongodb user module, an error message `"unable to connect to database: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists."` is displayed.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
- ansible version: 3.3.*
- python version: 3.12.1
```

##### COLLECTION VERSION

```paste below
community.mongodb 1.6.3  
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
PAGER(env: PAGER) = less

```

##### OS / ENVIRONMENT

- OS: amazonlinux:2.0.20230612.0
- database engine: docdb 5.0.0
##### STEPS TO REPRODUCE

```yaml
- name: Create database users
  mongodb_user:
    login_user: "{{ mongodb_root_credentials[item.instance].username }}"
    login_password: "{{ mongodb_root_credentials[item.instance].password }}"
    login_host: "{{ mongodb_endpoints[item.instance] }}"
    login_port: "{{ mongodb_ports[item.instance] }}"
    name: "{{ item.username }}"
    password: "{{ mongodb_user_credentials[item.instance][item.username] }}"
    roles: "{{ item.roles }}"
    state: "{{ item.state }}"
  with_items: "{{ mongodb_users }}"

```

##### EXPECTED RESULTS

- create users on aws documentdb 5.0 version

##### ACTUAL RESULTS

An error message was displayed. 

```paste below
"unable to connect to database: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists."
```

**Comment by rhysmeister** [comment]
Hello @Chaaany,

Have you forgotten to paste the loop seciton of your module call? e.g.

`
- name: Create database users
  mongodb_user:
    login_user: "{{ mongodb_root_credentials[item.instance].username }}"
    login_password: "{{ mongodb_root_credentials[item.instance].password }}"
    login_host: "{{ mongodb_endpoints[item.instance] }}"
    login_port: "{{ mongodb_ports[item.instance] }}"
    name: "{{ item.username }}"
    password: "{{ mongodb_user_credentials[item.instance][item.username] }}"
    roles: "{{ item.roles }}"
    state: "{{ item.state }}"
loop: "{{ mongodb_user_credentials }}"
`

Lots of examples here: https://github.com/ansible-collections/community.mongodb/blob/02e59814936ef2711722e5e21a79b29a03fa4230/tests/integration/targets/mongodb_user/tasks/main.yml#L100

It's also possible one of your dict lookups isn't correct so I'd double check those. Please note that DocumentDB is not officially supported (although would be fixed if easy).

Cheers,

Rhys

**Comment by Chaaany** [comment]
@rhysmeister Thank you for your comment.
I usually use postgresql ansible module like below template. 
And it was well compatible with the AWS Aurora RDS postgresql engine.
```
- name: Grant privileges on database to users
  postgresql_privs:
    login_user: "{{ rds_root_credentials[item.instance].username }}"
    login_password: "{{ rds_root_credentials[item.instance].password }}"
    login_host: "{{ aurora_endpoints[item.instance] }}"
    login_port: "{{ aurora_ports[item.instance] }}"
    db: "{{ item.db }}"
    roles: "{{ item.roles }}"
    privs: "{{ item.privs }}"
    type: "{{ item.type }}"
    state: "{{ item.state }}"
  with_items: "{{ aurora_database_privs }}"
  when:
    - item.instance is defined
  ```
I tried using DocumentDB and MongoDB on AWS because they were said to be compatible.
Expecting that the mongodb module would work well like the template, so I abbreviated it.
As you commented, I have to double check again. 

Thank you! Rhys

Chaaany.

**Comment by Chaaany** [comment]
> Hello @Chaaany,
> 
> Have you forgotten to paste the loop seciton of your module call? e.g.
> 
> ```yaml
> - name: Create database users
>   community.mongodb.mongodb_user:
>     login_user: "{{ mongodb_root_credentials[item.instance].username }}"
>     login_password: "{{ mongodb_root_credentials[item.instance].password }}"
>     login_host: "{{ mongodb_endpoints[item.instance] }}"
>     login_port: "{{ mongodb_ports[item.instance] }}"
>     name: "{{ item.username }}"
>     password: "{{ mongodb_user_credentials[item.instance][item.username] }}"
>     roles: "{{ item.roles }}"
>     state: "{{ item.state }}"
>   loop: "{{ mongodb_user_credentials }}"
> ```
> 
> Please note that you should also use the full module path. The ansible installation might come with an earlier version of the module.
> 
> Lots of examples here:
> 
> https://github.com/ansible-collections/community.mongodb/blob/02e59814936ef2711722e5e21a79b29a03fa4230/tests/integration/targets/mongodb_user/tasks/main.yml#L100
> 
> It's also possible one of your dict lookups isn't correct so I'd double check those. Please note that DocumentDB is not officially supported (although would be fixed if easy).
> 
> Cheers,
> 
> Rhys

@rhysmeister Thank you for your comment.
I usually use postgresql ansible module like below template. 
And it was well compatible with the AWS Aurora RDS postgresql engine.
```
- name: Grant privileges on database to users
  postgresql_privs:
    login_user: "{{ rds_root_credentials[item.instance].username }}"
    login_password: "{{ rds_root_credentials[item.instance].password }}"
    login_host: "{{ aurora_endpoints[item.instance] }}"
    login_port: "{{ aurora_ports[item.instance] }}"
    db: "{{ item.db }}"
    roles: "{{ item.roles }}"
    privs: "{{ item.privs }}"
    type: "{{ item.type }}"
    state: "{{ item.state }}"
  with_items: "{{ aurora_database_privs }}"
  when:
    - item.instance is defined
  ```
I tried using DocumentDB and MongoDB on AWS because they were said to be compatible.
Expecting that the mongodb module would work well like the template, so I abbreviated it.
As you commented, I have to double check again. 

Thank you! Rhys

Chaaany.
