### ISSUE TITLE
Module defaults support

### ISSUE THREAD

**Issue by 2bPro** [ansible-collections/community.mongodb#659]
##### SUMMARY

Modules share parameters such as `login_port`, `login_database`, `login_user`, and `login_password`. It would be very useful if these could be specified via module defaults like so:

```yaml
- name: Configure MongoDB block
  module_defaults:
  community.mongodb.all:
    login_host: "{{ config.host }}"
    login_port: "{{ config.port }}"
    login_user: "admin"
    login_password: "{{ vault_admin_password }}"
  block:
    - name: Configure roles
       community.mongodb.role:
         name: changeOwnPassword
         privileges:
           - resource:
                db: admin
                collection: ""
             actions:
                - changeOwnPassword
     - name: Configure users
       community.mongodb.user:
         name: manager
         password: "{{ vault_manager_password }}"
         roles:
           - db: admin
             role: changeOwnPassword
```

See [community.postgresql](https://github.com/ansible-collections/community.postgresql/blob/091993f7fd4ea7d29cf178d9a947ac8ad7781e23/meta/runtime.yml#L3) collection as an example for enabling this.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Collection-level configuration
