### ISSUE TITLE
Disable Transparent Huge Pages (THP)

### ISSUE THREAD

**Issue by tarek1375** [ansible-collections/community.mongodb#664]
##### SUMMARY
The THP is not disabled due to an error in mongodb_linux grep shell command.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
The problem is in the task, named "Check if disable-transparent-huge-pages service is already run"

##### ANSIBLE VERSION

```ansible [core 2.14.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/test/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/test/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/test/.local/bin/ansible
  python version = 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

```

##### COLLECTION VERSION

`community.mongodb 1.5.2  `

##### OS / ENVIRONMENT
Debian 11

##### STEPS TO REPRODUCE
Checking in my VM, which is mongo installed with this command:
```

cat /sys/kernel/mm/transparent_hugepage/enabled

[always] madvise never
```

When trying the shell command you have in your task, i got this result:
```
cat /sys/kernel/mm/transparent_hugepage/enabled | grep -o '[never]'
v
e
n
e
v
e
r
```

##### EXPECTED RESULTS
The result expected is that:
```
cat /sys/kernel/mm/transparent_hugepage/enabled

always madvise [never]
```

##### SOLUTION

Changing this task "Check if disable-transparent-huge-pages service is already run" from:

```
- name: Check if disable-transparent-huge-pages service is already run
  shell: cat /sys/kernel/mm/transparent_hugepage/enabled | grep -o '[never]'
  when: sys_thp.stat.exists
  register: _huge_page_status
  ignore_errors: yes
  changed_when: _huge_page_status.stdout == ""
  tags:
    - "linux"
    - "service"
    - "setup"
```

To this:

```
- name: Check if disable-transparent-huge-pages service is already run
  shell: cat /sys/kernel/mm/transparent_hugepage/enabled | grep -o '\[never\]'
  when: sys_thp.stat.exists
  register: _huge_page_status
  ignore_errors: yes
  changed_when: _huge_page_status.stdout == ""
  tags:
    - "linux"
    - "service"
    - "setup"
```
