### ISSUE TITLE
connection_option: "retrywrites=false" appears to be ignored (1.7.6)

### ISSUE THREAD

**Issue by randoneering** [ansible-collections/community.mongodb#677]
##### SUMMARY
When passing the connection_option "retryWrites=false" when using the community.mongodb_shell module, it seems the connection option is ignored. The target database instance is an AWS DocumentDB instance, so it is not an officially supported mongodb instance. However, I am able to run the same insert when manually connecting to the instance using mongosh and passing the connection option of "retryWrites=false." 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.mongodb.mongodb_shell

##### ANSIBLE VERSION

```
Ansible version is 2.15.0
```

##### COLLECTION VERSION

```
community.mongodb version is 1.7.6

```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
HOST_KEY_CHEKCING(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

RHEL 8

##### STEPS TO REPRODUCE

```yaml
---
- name: Initialization of MongoDB Instance
  hosts: all
  tasks:
    - name: Create database
      community.mongodb.mongodb_shell:
          login_host: "{{ mongodb_host }}"
          login_database: foo
          login_user: "{{ db_username }}"
          login_password: "{{ db_password }}"
          login_port: 27017
          eval: 'db.scriptResults.insertOne({ "name": dba_init", "status": "ran", "execution": new Date() })'
          ssl: true
         ssl_ca_certs: "pathtocert"
         connection_options:
             - "retryWrites=false"
```

##### EXPECTED RESULTS

The insert is successful

##### ACTUAL RESULTS

```json
{
   "msg": "MongoServerError: Retryable writes are not supported",
   "invocation": {
      "module_args": {
         "login_host": "foobar.rds.instance",
         "login_database": "foo",
         "login_user": "redacted",
         "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
         "login_port": 27017,
         "eval": "EJSON.stringify(db.scriptResults.insertOne({ \"name\": \"dba_init\", \"status\": \"ran\", \"execution\": new Date() }))",
         "ssl": true,
         "ssl_ca_certs": "redacted",
         "connection_options": [
            "retrywrites=false"
         ],
         "strict_compatibility": true,
         "atlas_auth": false,
         "ssl_cert_reqs": "CERT_REQUIRED",
         "mongo_cmd": "mongosh",
         "db": "test",
         "nodb": false,
         "norc": false,
         "quiet": true,
         "debug": false,
         "transform": "auto",
         "split_char": " ",
         "idempotent": false,
         "omit": [],
         "ssl_crlfile": null,
         "ssl_certfile": null,
         "ssl_keyfile": null,
         "ssl_pem_passphrase": null,
         "auth_mechanism": null,
         "file": null,
         "stringify": true,
         "additional_args": null
      }
   },
   "_ansible_no_log": null,
   "changed": false
}
```
