### ISSUE TITLE
Unable to configure members priorities on an existing replicaset

### ISSUE THREAD

**Issue by BapRx** [ansible-collections/community.mongodb#702]
##### SUMMARY

I created a replicaset without specifying priorities. I tried to update the replicaset by configuring the priorities and setting `reconfigure` to `true` but the update fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`mongodb_replicaset`

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.14]
python version = 3.12.6
```

##### COLLECTION VERSION

```paste below
1.7.9
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

Debian 12

##### STEPS TO REPRODUCE

```yaml
---
- name: Configure MongoDB Replicaset
  community.mongodb.mongodb_replicaset:
    login_database: admin
    login_host: localhost
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ mongodb_admin_pwd }}"
    reconfigure: true
    replica_set: "{{ repl_set_name }}"
    members:
      - host: "member-1.{{ env }}.internal"
        priority: 30
      - host: "member-2.{{ env }}.internal"
        priority: 20
      - host: "member-3.{{ env }}.internal"
        priority: 10
  register: repl

- name: Ensure replicaset has reached a converged state
  community.mongodb.mongodb_status:
    replica_set: "{{ repl_set_name }}"
    poll: 10
    interval: 10
  when: repl.changed == True
```

##### EXPECTED RESULTS

`changed: [member-1]`

##### ACTUAL RESULTS

`fatal: [member-1]: FAILED! => {"changed": false, "module_stderr": "Pseudo-terminal will not be allocated because stdin is not a terminal.\r\nTraceback (most recent call last):\n  File \"<stdin>\", line 107, in <module>\n  File \"<stdin>\", line 99, in _ansiballz_main\n  File \"<stdin>\", line 47, in invoke_module\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_community.mongodb.mongodb_replicaset_payload_hbq4oqqr/ansible_community.mongodb.mongodb_replicaset_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_replicaset.py\", line 615, in <module>\n  File \"/tmp/ansible_community.mongodb.mongodb_replicaset_payload_hbq4oqqr/ansible_community.mongodb.mongodb_replicaset_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_replicaset.py\", line 586, in main\n  File \"/tmp/ansible_community.mongodb.mongodb_replicaset_payload_hbq4oqqr/ansible_community.mongodb.mongodb_replicaset_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_replicaset.py\", line 493, in modify_members_flow\n  File \"/tmp/ansible_community.mongodb.mongodb_replicaset_payload_hbq4oqqr/ansible_community.mongodb.mongodb_replicaset_payload.zip/ansible_collections/community/mongodb/plugins/module_utils/mongodb_common.py\", line 427, in member_dicts_different\nTypeError: list indices must be integers or slices, not NoneType\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`

The rs configuration on the cluster is:

```shell
rs0 [direct: primary] test> rs.conf()
{
  _id: 'rs0',
  version: 1,
  term: 1,
  members: [
    {
      _id: 0,
      host: 'member-1.dev.internal:27017',
      arbiterOnly: false,
      buildIndexes: true,
      hidden: false,
      priority: 1,
      tags: {},
      secondaryDelaySecs: Long('0'),
      votes: 1
    },
    {
      _id: 1,
      host: 'member-2.dev.internal:27017',
      arbiterOnly: false,
      buildIndexes: true,
      hidden: false,
      priority: 1,
      tags: {},
      secondaryDelaySecs: Long('0'),
      votes: 1
    },
    {
      _id: 2,
      host: 'member-3.dev.internal:27017',
      arbiterOnly: false,
      buildIndexes: true,
      hidden: false,
      priority: 1,
      tags: {},
      secondaryDelaySecs: Long('0'),
      votes: 1
    }
  ],
  protocolVersion: Long('1'),
  writeConcernMajorityJournalDefault: true,
  settings: {
    chainingAllowed: true,
    heartbeatIntervalMillis: 2000,
    heartbeatTimeoutSecs: 10,
    electionTimeoutMillis: 10000,
    catchUpTimeoutMillis: -1,
    catchUpTakeoverDelayMillis: 30000,
    getLastErrorModes: {},
    getLastErrorDefaults: { w: 1, wtimeout: 0 },
    replicaSetId: ObjectId('6824920e7b972d3b985bd9e1')
  }
}
```
