### ISSUE TITLE
Add support for MongoDB SRV connection strings

### ISSUE THREAD

**Issue by Fuzzicles** [ansible-collections/community.mongodb#706]
##### SUMMARY

I'd like support for the `srv` connection format in the `community.mongodb.mongodb_shell` and `community.mongodb.mongodb_index` modules. I have a mongo instance sitting behind a service DNS record whose IP I do not know that I'd like to manage with ansible. Ideally, all mongodb modules would support this format.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.mongodb.mongodb_shell

##### ADDITIONAL INFORMATION

Currently any mongodb instance sitting behind a `srv` DNS record is inaccessible by any of the mongodb modules. I propose adding another option to these 2 modules that indicates the host being connected to is sitting behind a service record and to set the connection string accordingly. 

Here's a link to MongoDBs SRV connection format docs
- https://www.mongodb.com/docs/manual/reference/connection-string/#srv-connection-format

```yaml
- name: Get version of SRV record mongodb host
  community.mongodb.mongodb_shell:
    login_user: user
    login_password: secret
    login_host: "some-hostname.example.com"
    eval: "db.version()"
    srv: true
```
